unreal:
  path:  C:/Users/vinic/OneDrive/Mestrado/Programa/Python/data/control
  file: control.txt

detect:
  vertical_limit: 20
  horizontal_limit: 20
  min_distance: 10
  max_progress_data: 8

sensors:
  ADS-B:
    reader_path: C:/Users/vinic/OneDrive/Mestrado/Programa/Python/data/log_aviao
    reader_file_prefix: log_voo
    ADS-B_header:
      - icao24
      - callsign
      - origin_country
      - time_position
      - x_position
      - y_position
      - barometric_altitude
      - on_ground
      - velocidade
      - heading
      - vertical_rate
      - geo_altitude
      - squawk
      - spi
      - position_source

  LIDAR:
    save_path: ../data/cloud_points/
    save_file_prefix: test

  Vision:
    show_video: true
    min_area: 350
