tracker:
  tld: cv2.TrackerTLD
  boosting: cv2.TrackerBoosting
  kcf: cv2.TrackerKCF
  csrt: cv2.TrackerCSRT
  mil: cv2.TrackerMIL
detect:
  mog:
    class: DetectMog
    file: null
    prep_data: null
    param: null
  svm:
    class: DetectML
    file: svm.sav
    prep_data: pca
    param: null
  neural:
    class: DetectML
    file: neural.sav
    prep_data: null
    param: null
prep_data:
  pca:
    class: null
    file: null
    param: null
execution:
  only_detect: true
  train: false
  dir_model:  ../data/models/